package cn.mrpei.bean;

// default package
// Generated 2016-10-11 19:24:21 by Hibernate Tools 5.2.0.Beta1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String name;
	private String sex;
	private String nation;
	private String nativePlace;
	private Integer studentNumber;
	private String birthday;
	private String politicsStatus;
	private String class_;
	private String phone;
	private String qq;
	private String email;
	private String sushe;
	private String department;
	private String adjust;
	private String info;
	private String remark;
	private String time;
	private String devices;
	private String operatingSystem;
	private String browser;
	private String ip;

	public Users() {
	}

	public Users(String department) {
		this.department = department;
	}

	public Users(String name, String sex, String nation, String nativePlace, Integer studentNumber, String birthday,
			String politicsStatus, String class_, String phone, String qq, String email, String sushe,
			String department, String adjust, String info, String remark, String time, String devices,
			String operatingSystem, String browser, String ip) {
		this.name = name;
		this.sex = sex;
		this.nation = nation;
		this.nativePlace = nativePlace;
		this.studentNumber = studentNumber;
		this.birthday = birthday;
		this.politicsStatus = politicsStatus;
		this.class_ = class_;
		this.phone = phone;
		this.qq = qq;
		this.email = email;
		this.sushe = sushe;
		this.department = department;
		this.adjust = adjust;
		this.info = info;
		this.remark = remark;
		this.time = time;
		this.devices = devices;
		this.operatingSystem = operatingSystem;
		this.browser = browser;
		this.ip = ip;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getNativePlace() {
		return this.nativePlace;
	}

	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	public Integer getStudentNumber() {
		return this.studentNumber;
	}

	public void setStudentNumber(Integer studentNumber) {
		this.studentNumber = studentNumber;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getPoliticsStatus() {
		return this.politicsStatus;
	}

	public void setPoliticsStatus(String politicsStatus) {
		this.politicsStatus = politicsStatus;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSushe() {
		return this.sushe;
	}

	public void setSushe(String sushe) {
		this.sushe = sushe;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getAdjust() {
		return this.adjust;
	}

	public void setAdjust(String adjust) {
		this.adjust = adjust;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getDevices() {
		return this.devices;
	}

	public void setDevices(String devices) {
		this.devices = devices;
	}

	public String getOperatingSystem() {
		return this.operatingSystem;
	}

	public void setOperatingSystem(String operatingSystem) {
		this.operatingSystem = operatingSystem;
	}

	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
